/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h" //"" 导入当前目录下的 <>到入系统的
/* Header for class com_demo_ndk_NdkSimple */

//用来打一个标记，C在编译的时候会把头文件copy到你引入的地方，不管是重复引用还是相互引用都只会copy一次
#ifndef _Included_com_demo_ndk_NdkSimple
#define _Included_com_demo_ndk_NdkSimple
#ifdef __cplusplus //相当于if语句c++ 

//统一采用C编译方式，因为在c里面是不允许函数重载，确保jni开发的函数是唯一的
extern "C" {
#endif
/*
 * Class:     com_demo_ndk_NdkSimple
 * Method:    getStringnaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_ndk_NdkSimple_getStringnaturePassword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
