/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_demo_ndk_NdkSimple4 */

#ifndef _Included_com_demo_ndk_NdkSimple4
#define _Included_com_demo_ndk_NdkSimple4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_ndk_NdkSimple4
 * Method:    sort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple4_sort
  (JNIEnv *, jclass, jintArray);

JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple4_localRef
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple4_saveGlobalRef
(JNIEnv *, jclass,jstring);

JNIEXPORT jstring JNICALL Java_com_demo_ndk_NdkSimple4_getGlobalRef
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple4_staticLocalCache
(JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple4_initStaticCache
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple4_exception
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
