/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_demo_ndk_NdkSimple3 */

#ifndef _Included_com_demo_ndk_NdkSimple3
#define _Included_com_demo_ndk_NdkSimple3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_ndk_NdkSimple3
 * Method:    callStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple3_callStaticMethod
  (JNIEnv *, jclass);

JNIEXPORT jobject JNICALL Java_com_demo_ndk_NdkSimple3_createPoint
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
