/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_demo_ndk_NdkSimple2 */

#ifndef _Included_com_demo_ndk_NdkSimple2
#define _Included_com_demo_ndk_NdkSimple2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_ndk_NdkSimple2
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple2_changeName
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple2_changeAge
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_demo_ndk_NdkSimple2_callAddMethod
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
